version: '3.8'

services:
  backend:
    build:
      context: ./Back/spaintrips/my-project/my-project
    container_name: spaintrips-backend
    ports:
      - "8000:8000"  # Ajusta si Laravel escucha en otro puerto
    volumes:
      - ./Back/spaintrips/my-project/my-project:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: spaintrips-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: spaintrips-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spaintrips
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
