services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_DATABASE=spaintrips
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel

  laravel:
    image: bitnami/laravel:latest
    container_name: laravelSpainTrips
    restart: always
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=admin123
      - DB_DATABASE=spaintrips
    volumes:
      - ./my-project:/app
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    networks:
      - laravel
    command: ["tail", "-f", "/dev/null"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=admin123
    depends_on:
      - mariadb
    networks:
      - laravel

volumes:
  mariadb_data:

networks:
  laravel:
